import { JsonEvidence } from "./JsonEvidence";
import {useEffect,useState} from 'react';
import {BookOpen,ArrowRight,Download,Search,Copy,ChevronLeft} from 'lucide-react';
import './omaro.css';
type Row=Record<string,any>;
const ROOT='/vocab/omaro';
const titles:Record<string,string>={instruments:'Instrument names',hs:'Hornbostel–Sachs',ontology:'OMARO ontology'};
const pretty=(s:string)=>s.replace(/_/g,' ').replace(/-/g,' ');
function useData(url:string):{data?:Row,error?:string,missing?:boolean}{
 const [state,set]=useState<{url:string,data?:Row,error?:string,missing?:boolean}>();
 useEffect(()=>{const controller=new AbortController();fetch(url,{signal:controller.signal}).then(async r=>{if(r.status===404&&url==='/api/omaro'){set({url,missing:true});return;}const data=await r.json();if(!r.ok)throw new Error(data.error||'Reference unavailable');set({url,data});}).catch(e=>{if(!controller.signal.aborted)set({url,error:e.message});});return()=>controller.abort();},[url]);
 return state?.url===url?state:{};
}
function Evidence({value,label='Retained evidence'}:{value:any,label?:string}){return <details className="om-evidence"><summary>{label}</summary><JsonEvidence value={value} label={label}/></details>;}
export function OmaroCard({query=''}:{query?:string}){
 const {data,error,missing}=useData('/api/omaro');
 if(missing||!('omaro mimo instrument names hornbostel sachs ontology reference classification'.includes(query.toLowerCase())))return null;
 if(error)return <p role="alert">OMARO reference unavailable: {error}</p>;
 if(!data)return null;
 return <section className="om-entry" aria-label="OMARO reference collections"><div><p className="eyebrow">Additional reference collections · Private release</p><h2>OMARO</h2><p>Instrument names, classification and the evidence behind an organological assertion.</p><p>{data.counts.classifications.toLocaleString()} classifications · {data.counts.instruments.toLocaleString()} instrument concepts · 13 languages</p><small>Separate from the POD vocabularies. Ontology {data.ontologyVersion} · Reference dataset {data.datasetVersion}</small></div><div className="om-entry-links">{Object.entries(titles).map(([key,title])=><a key={key} href={ROOT+'?collection='+key+'&snapshot='+data.snapshotSha256}>{title}<ArrowRight size={16} aria-hidden="true"/></a>)}</div></section>;
}
export function OmaroExplorer(){
 const [search,setSearch]=useState(location.search);const params=new URLSearchParams(search);const collection=params.get('collection')||'instruments';const uri=params.get('uri');const context=useData('/api/omaro');const meta=context.data;const [notice,setNotice]=useState('');
 useEffect(()=>{const change=()=>setSearch(location.search);window.addEventListener('popstate',change);return()=>window.removeEventListener('popstate',change);},[]);
 useEffect(()=>{document.title='OMARO reference | MODAVIS Navigator';if(meta&&!params.get('snapshot')){const next=new URLSearchParams(search);next.set('snapshot',meta.snapshotSha256);history.replaceState({},'',ROOT+'?'+next);setSearch(location.search);}},[meta,search]);
 // The browser starts with source concepts; the API's unfiltered contract stays unchanged.
 const resolution=params.get('resolution')||'resolved';
 const api=new URLSearchParams(params);api.delete('collection');if(!uri)api.set('collection',collection);
 if(!uri&&collection!=='ontology'&&resolution!=='all')api.set('resolution',resolution);else api.delete('resolution');
 const result=useData('/api/omaro/'+(uri?'concept?':'concepts?')+api);const data=result.data;
 function go(values:Row,reset=false){const next=reset?new URLSearchParams():new URLSearchParams(search);for(const [k,v] of Object.entries(values)){if(v===null||v==='')next.delete(k);else next.set(k,String(v));}if(params.get('snapshot'))next.set('snapshot',params.get('snapshot')!);else if(meta)next.set('snapshot',meta.snapshotSha256);history.pushState({},'',ROOT+'?'+next);setSearch(location.search);setNotice('');}
 function href(value:string){const next=new URLSearchParams(search);next.set('uri',value);return ROOT+'?'+next;}
 const localLink=(value:string,label?:string)=><a href={href(value)} onClick={e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();go({uri:value});}}>{label||value.split(/[\/#]/).pop()}</a>;
 const mismatch=meta&&params.get('snapshot')&&params.get('snapshot')!==meta.snapshotSha256;
 const exports=meta?Object.entries(meta.exports) as [string,Row][]:[];
 return <section className="om-page" aria-label="OMARO reference browser"><a href="/vocab" className="om-back"><ChevronLeft size={16} aria-hidden="true"/> All vocabularies</a>
 <header className="om-hero"><p className="eyebrow">Ontology for Multiperspectivity, Assertions, and Review in Organology</p><h1>OMARO reference</h1><p>Explore instrument concepts and classifications. Follow the source wording, perspective and evidence behind each statement.</p>{meta&&<div className="om-badges"><span>Dataset {meta.datasetVersion}</span><span>Ontology {meta.ontologyVersion}</span><span>Private GitHub release</span><span>CC0</span></div>}</header>
 <nav className="om-tabs" aria-label="OMARO collections">{Object.entries(titles).map(([key,title])=><button key={key} aria-pressed={collection===key} onClick={()=>go({collection:key},true)}>{title}</button>)}</nav>
 {context.error&&<p role="alert">{context.error}</p>}{context.missing&&<p role="alert">OMARO is not configured in this Navigator snapshot.</p>}
 {mismatch&&<p role="alert">This link refers to a different OMARO snapshot. Its results are unavailable in this preview.</p>}
 <p className="om-boundary">{collection==='ontology'?'Ontology classes and properties describe the assertion model. They are distinct from SKOS instrument concepts and physical instruments.':'These are MIMO-derived reference concepts. A source classification or matching name does not establish a classification of a particular POD organ. Labels and classification assertions remain unreviewed source evidence.'}</p>
 {!uri&&<form className="om-search" key={search} onSubmit={e=>{e.preventDefault();go({...Object.fromEntries(new FormData(e.currentTarget)),offset:0});}}><label><span>Search {titles[collection]||'reference'}</span><div><Search size={18} aria-hidden="true"/><input name="q" defaultValue={params.get('q')||''} maxLength={200} placeholder={collection==='ontology'?'Assertion, scope, review…':'Name in any language or classification code'}/></div></label>{collection!=='ontology'&&<><label>Display language<select name="language" defaultValue={params.get('language')||'en'}>{[['en','English'],['de','Deutsch'],['fr','Français'],['it','Italiano'],['es','Español'],['nl','Nederlands'],['ca','Català'],['da','Dansk'],['eu','Euskara'],['ko','한국어'],['pl','Polski'],['sv','Svenska'],['zh','中文']].map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label><label>Record scope<select name="resolution" defaultValue={resolution}><option value="resolved">Source concepts</option><option value="unresolved">Unresolved references</option><option value="all">All records</option></select></label></>}<button type="submit">Search</button></form>}
 {!uri&&collection!=='ontology'&&<p className="om-scope-note">{resolution==='resolved'?<>Showing concepts with source records. <button onClick={()=>go({resolution:'unresolved',offset:0})}>Browse unresolved source references</button></>:resolution==='unresolved'?<>These identifiers occur in source relationships, but their concept records are absent from this snapshot. <button onClick={()=>go({resolution:'resolved',offset:0})}>Browse concepts with source records</button></>:<>Showing source concepts and unresolved references together.</>}</p>}
 {uri&&<button className="om-back" onClick={()=>go({uri:null})}><ChevronLeft size={16} aria-hidden="true"/> Back to results</button>}
 {result.error&&<p role="alert">{result.error}</p>}{!data&&!result.error&&<p role="status">Loading reference evidence…</p>}
 {data&&!mismatch&&!uri&&<><div className="om-result-bar" role="status">{data.total.toLocaleString()} {collection==='ontology'?'ontology resources':resolution==='resolved'?'source concepts':resolution==='unresolved'?'unresolved source references':'reference records'} · {data.total?data.offset+1:0}–{Math.min(data.total,data.offset+data.items.length)}</div>{!data.total&&<p className="om-empty">No records match these filters. Try another term or change the record scope.</p>}<div className="om-results">{data.items.map((x:Row)=><article key={x.uri}><span className="om-kind">{x.kind==='classification'?x.notation:x.kind==='instrument'?'Instrument concept':pretty(x.kind)}</span><h2>{localLink(x.uri,x.label)}</h2>{x.definition&&<p>{x.definition}</p>}{x.resolution==='unresolved'&&<p className="om-unresolved">Unresolved source reference · no definition or identity inferred</p>}<small>{x.uri}</small></article>)}</div><nav className="om-pagination" aria-label="OMARO result pages"><button disabled={data.offset===0} onClick={()=>go({offset:Math.max(0,data.offset-data.limit)})}>Previous</button><span>Page {Math.floor(data.offset/data.limit)+1}</span><button disabled={!data.hasMore} onClick={()=>go({offset:data.offset+data.limit})}>Next</button></nav></>}
 {data&&!mismatch&&uri&&<article className="om-detail"><p className="eyebrow">{data.kind==='ontology-term'?data.kind:pretty(data.concept.kind)}</p><h2>{data.label||data.concept.label}</h2><div className="om-identity"><code>{uri}</code><button onClick={async()=>{try{await navigator.clipboard.writeText(uri);setNotice('Canonical URI copied.');}catch{setNotice('Select and copy the canonical URI above.');}}}><Copy size={15} aria-hidden="true"/> Copy URI</button></div>{notice&&<p role="status">{notice}</p>}
 {data.kind==='ontology-term'?<><p>{data.definition}</p><h3>Term relationships</h3><dl className="om-statements">{data.statements.map((s:Row,i:number)=><div key={i}><dt>{s.predicate.split(/[\/#]/).pop()}</dt><dd>{s.kind==='uri'&&s.value.startsWith('https://w3id.org/modavis/omaro#')?localLink(s.value):s.kind==='blank'?'OWL expression · see complete ontology download':s.value}{s.language&&<small> ({s.language})</small>}</dd></div>)}</dl><Evidence value={data.statements} label="Exact retained RDF statements"/></>:<>
 {data.concept.resolution==='unresolved'&&<p className="om-unresolved">This source reference is unresolved. No instrument identity or preferred label is inferred.</p>}
 {data.concept.notation&&<p><strong>Classification notation:</strong> {data.concept.notation}</p>}<p>{data.concept.definition||'No source definition recorded.'}</p>
 <h3>Source labels</h3><div className="om-table"><table><thead><tr><th>Language</th><th>Wording</th><th>Source label role</th></tr></thead><tbody>{(data.records.labels||[]).map((l:Row,i:number)=><tr key={i}><td>{l.language}{l.submitted_language&&l.submitted_language!==l.language&&<small>Source tag: {l.submitted_language}</small>}</td><td lang={l.language==='und'?undefined:l.language}>{l.label}</td><td>{l.label_type}</td></tr>)}</tbody></table></div>
 <h3>Hierarchy and source relations</h3>{data.relations.length===0&&<p>No source relations recorded.</p>}<ul className="om-relations">{data.relations.map((r:Row,i:number)=><li key={i}><span>{r.predicate_uri.endsWith('#broader')?(r.direction==='outgoing'?'Broader concept':'Narrower concept'):(r.direction==='incoming'?'Incoming ':'')+r.predicate_uri.split('#').pop()}</span>{localLink(r.other.uri,(r.other.notation?r.other.notation+' · ':'')+r.other.label)}{r.predicate_uri.endsWith('#exactMatch')&&<small>Original MIMO mapping · retained source layer, not project endorsement</small>}</li>)}</ul>
 <h3>Qualified classification evidence</h3><p>Source-asserted occurrences remain distinct from assignment activities and review decisions. Source-silent applicability is unknown, not universal validity.</p>{!(data.records.classification_assertions||[]).length&&<p>No classification assertion is recorded for this concept.</p>}{(data.records.classification_assertions||[]).map((a:Row)=><section className="om-assertion" key={a.uri}><p>{localLink(a.target_uri)} → {localLink(a.classification_uri)}</p><p>{a.stance} · {a.target_type} · {a.assertion_origin}</p><Evidence value={a} label="Scope, evidence, provenance and assertion identity"/></section>)}
 <p className="om-boundary">{data.podClassificationStatus}</p><details><summary>All retained concept evidence and registry context</summary>{Object.entries(data.records).map(([kind,rows])=><Evidence key={kind} value={rows} label={pretty(kind)}/>)}<Evidence value={data.registry} label="Perspectives, source-silent scope, source records and projection policies"/></details>
 </>}
 <a className="om-download" href={'/api/omaro/concept?uri='+encodeURIComponent(uri)+'&snapshot='+data.snapshotSha256} download="omaro-reference-evidence.json"><Download size={16} aria-hidden="true"/> Download reference evidence · JSON</a></article>}
 {meta&&!mismatch&&<details className="om-distributions"><summary>Snapshot, citation and original distributions</summary><p>OMARO. Reference Dataset {meta.datasetVersion}; Ontology {meta.ontologyVersion}. Private GitHub release v1.0.0. Source commit {meta.sourceCommit}.</p><p>Snapshot SHA-256: <code>{meta.snapshotSha256}</code></p><p>The intended W3ID identifiers and reserved DOI are not asserted to be publicly active. MIMO source identifiers are retained. This reference does not add supporting sources to POD organs.</p><div className="om-downloads">{exports.map(([key,value])=><a key={key} href={'/api/omaro/download/'+key+'?snapshot='+meta.snapshotSha256}><Download size={15} aria-hidden="true"/>{value.file}</a>)}</div><Evidence value={meta} label="Version bindings, source checksums and coverage"/></details>}
 </section>;
}
