/** Public interpretation guidance. Keep record-specific qualifications beside the evidence. */
export type FaqItem = { id: string; question: string; answer: string; link?: { href: string; label: string } };
export type FaqSet = { id: string; label: string; items: FaqItem[] };
const item = (id: string, question: string, answer: string, href?: string, label?: string): FaqItem => ({ id, question, answer, ...(href && label ? { link: { href, label } } : {}) });
const source = item('sources', 'Do several sources mean independent confirmation?', 'Source counts describe retained source records or collections. Collections may reuse information, and their accounts can disagree. Open the source references and compare the particular claim, date and instrument before treating them as independent confirmation.');
const missing = item('missing', 'Does missing information mean a feature did not exist?', 'No. A source may omit a detail, the available account may be partial, or the detail may not yet be structured in this release. Check other source accounts and their original references before drawing a conclusion from an empty field.');
const dates = item('dates', 'Does “Current source listing” describe the organ today?', 'It identifies the source’s main account. A source capture or revision date does not establish the date of the instrument’s configuration. Check the account’s date qualification, historical descriptions and event links before treating it as a present-day state.');
const identity = item('identity', 'Why are some participants or builders unlinked?', 'The source wording can be retained without a sufficiently established canonical identity. Similar names, shared organs and family names alone do not establish that two mentions refer to the same person or workshop. Follow the source and any attribution notes; an absent warning is not proof that every attribution was independently verified.');
const citation = item('citation', 'Which link should I cite?', 'Use the record’s citation or identifier where available, and record the dataset version. For a filtered research result, keep the snapshot-bound link and its evidence download. A page URL, a canonical entity identifier and a source URL serve different purposes.', '/about/release', 'Dataset versions and citation');
const exportEvidence = item('export', 'Does an evidence download include just this page?', 'On source-term and research pages, the complete evidence download covers the selected filters, independently of display pagination. Export limits are stated beside the control; an oversized selection is rejected rather than silently truncated. Grouped chart downloads contain aggregates, while occurrence downloads contain the supporting rows.');
const stopMatch = item('stop-matching', 'Why can a known stop be missing from an exact search?', 'On a term’s usage page, exact wording ignores case and repeated spaces, but retains numbers and modifiers. Some sources store “Vox Humana 8” as the name even though pitch is also recorded separately, so it does not exactly match “Vox Humana”. Try “Wording containing this text” and check the results: it can also include “Vox Humana Echo”. The organ search narrows the current term selection; it does not broaden the stop wording.', '/vocab/usage/stops?q=Vox+Humana', 'Browse the recorded Vox Humana wordings');
const termIdentity = item('term-identity', 'Do matching names identify equivalent stops or instruments?', 'A text match groups recorded wording for discovery. It does not establish the same construction, sound, historical meaning or physical component. Keep pitch, division, source account and qualifiers such as “Echo” in view. A source wording or candidate mapping is not automatically a governed vocabulary concept.');
const counts = item('term-counts', 'Why do occurrences, accounts and organ counts differ?', 'An occurrence is one retained entry or event assertion. One organ can have several entries and several source accounts. For stops and divisions, percentages compare matching accounts with accounts containing recorded entries of that family in the same group and source scope. Activity charts use documented event records instead. The denominator is measured before term matching. Accounts and organs may appear in several groups, so group totals are not necessarily additive.');
const snapshots = item('snapshots', 'Why are research links long, and how do I repeat a result?', 'The snapshot identifies the exact public data used for the selection. Keep it together with the term, matching rule and filters, and save the evidence or aggregate export for the view you used. A snapshot mismatch means that selection cannot be reproduced on the available inputs; removing the snapshot changes the question’s data context.');
const eventMeaning = item('events', 'Are similarly worded events necessarily the same event?', 'No. A controlled activity type and the original source wording express different levels of description. Date, source, participants and context are needed to establish correspondence. Similar or undated entries may remain separate when the evidence does not justify reconciliation.');
const network = item('network', 'Does a line between builders prove collaboration?', 'Read the selected relationship: shared organs, joint participation in a documented event, or earlier/later work. Shared instruments do not establish collaboration, employment, apprenticeship or workshop succession. Inspect the supporting events and attribution notes before making a historical claim.');
const networkCount = item('network-counts', 'Why does the diagram show fewer connections than the total?', 'The diagram presents a page of connections around the selected actor. The accompanying table, pagination and complete network export provide the wider selection. Line weight represents the displayed count, not historical importance; links between other nodes are not implied.');
const compare = item('comparison', 'Does a difference between accounts establish a change to the organ?', 'A missing entry in one account may reflect incomplete documentation, a different description or an unresolved correspondence. Compare coverage, dates, source revisions, divisions and pitches first. Similar stop names do not by themselves prove physical continuity, addition or removal.');
const precision = item('precision', 'Does a map marker identify the exact organ location?', 'Check the coordinate precision and provenance. An approximate locality point can support regional discovery without identifying a venue. The source-listed place, an enriched place identity and a coordinate assertion are separate pieces of evidence.');
const media = item('media', 'Why must some images be loaded from their source?', 'Many media records are credited references hosted by another provider. A retained reference does not guarantee that the file is still available. Use the source link and credit shown with the image; image availability and permission to reuse it are separate questions.');
const vocab = item('vocabulary', 'Why do the vocabulary collections contain different kinds of terms?', 'Controlled concepts have established vocabulary identifiers and any available definitions. Source terminology records wording actually used in the corpus; candidate concepts retain their stated status. The hub brings these collections together while keeping their meanings and identifier status distinct.', '/vocab', 'Open the vocabulary hub');
const vocabLinks = item('vocab-links', 'How do I find records using a particular term?', 'Follow the concept’s related evidence links or browse the recorded event, stop and division wording. Search variants when needed: a controlled concept and a similar source label need not have an established mapping. A zero result means no match under the chosen scope, not that the term never occurred historically.');
const omaro = item('omaro', 'Does OMARO classify the organs in POD?', 'OMARO is a separate reference vocabulary of instrument names, classifications and assertions. Showing it in Navigator does not assign its classifications to POD organs. Use the concept URI, collection and reference snapshot shown on the page when citing it.');
const omaroUnresolved = item('omaro-unresolved', 'What does an unresolved source reference mean?', 'A source refers to a resource whose definition or identity is not established in this reference snapshot. The reference remains inspectable without an inferred definition or an invented equivalence. Use the record-scope control to include these references when investigating coverage.');
const set = (id: string, label: string, ...items: FaqItem[]): FaqSet => ({ id, label, items });

export function pageFaq(pathname: string, organTab = 'overview'): FaqSet | null {
 const path = pathname.replace(/\/+$/, '') || '/';
 if (path === '/vocab/usage/stops') return set('stops', 'Stop terminology', stopMatch, termIdentity, counts, exportEvidence);
 if (/^\/vocab\/usage\/(activities|divisions)$/.test(path)) return set('source-terms', 'Source terminology', item('wording-match', 'What does exact wording match?', 'Exact lookup ignores case and repeated spaces. Additional words, numbers and punctuation remain significant. Use the broader containing-text option to find variants, then inspect their original wording and context; similar wording is not automatically the same event or concept.'), counts, vocabLinks, snapshots);
 if (path === '/vocab/omaro') return set('omaro', 'OMARO reference', omaro, omaroUnresolved, item('omaro-evidence', 'Do source assertions establish equivalence between concepts?', 'Inspect the relation, source and reference snapshot. A name, classification membership or source assertion has its own meaning and should not be treated as a stronger identity or equivalence claim. Definitions are available only where supplied in the reference evidence.'));
 if (path === '/vocab' || /^\/vocab\/[^/]+(?:\/[^/]+(?:\/[^/]+)?)?$/.test(path)) return set('vocabulary', 'Vocabulary and source wording', vocab, vocabLinks, citation);
 if (path === '/use-cases/builder-workshop-networks') return set('networks', 'Builder and workshop networks', network, networkCount, identity, source);
 if (path === '/use-cases/research-workbench') return set('workbench', 'Research workbench', compare, identity, exportEvidence, snapshots);
 if (path === '/use-cases/regional-organ-stop-names') return set('regional-stops', 'Regional stop-name research', termIdentity, item('regional-country', 'Do country patterns represent historical traditions?', 'The country groups describe source-listed locations in this data snapshot. They do not establish a historical workshop location, a commission’s destination or a representative sample of a regional tradition. Check coverage by source and the evidence for any historical interpretation.'), missing, snapshots);
 if (path === '/use-cases/organ-corpus-coverage') return set('coverage', 'Corpus coverage', source, missing, item('coverage-sums', 'Can I add the collection totals?', 'Collection memberships overlap when several sources describe the same canonical organ. Features also overlap: one organ may have events, specifications and media. Use the explicitly labelled distinct-organ total rather than adding source or feature counts.'));
 if (path === '/use-cases/documented-organ-lifecycles') return set('lifecycles', 'Documented histories', dates, eventMeaning, source);
 if (path === '/use-cases/dalmatia-pipe-organs-fire-vulnerability') return set('fire', 'Historical spatial analysis', item('fire-current', 'Is this a current fire or damage assessment?', 'No. This is a dated analytical snapshot. Read its observation cutoff and organ-data version. Proximity to an observed fire perimeter does not establish damage, destruction or current risk at an organ.'), precision, item('fire-missing', 'Are unshown organs necessarily outside the affected area?', 'The analysis depends on its stated spatial coverage and eligible coordinate-backed records. Missing or approximate locations can prevent an organ from entering the analysis. Review those exclusions before interpreting an absent point.'));
 if (path === '/use-cases') return set('research', 'Research starting points', source, missing, snapshots);
 if (/^\/organs\/[^/]+\/components\/[^/]+\/pipe-positions\/[^/]+$/.test(path)) return set('pipe-position', 'Pipework evidence', item('pipe-position', 'Is a functional pipe position a surviving physical pipe?', 'A position describes a function within the documented specification. It does not by itself establish an observed or surviving pipe. Inspect the component, source evidence and any stated physical-object link.'), compare, citation);
 if (/^\/organs\/[^/]+$/.test(path)) {
  if (organTab === 'specification') return set('specification', 'Specifications and source accounts', dates, item('stop-totals', 'Why can totals differ from the displayed stop rows?', 'A source-reported total, a detailed account and a count of delivered rows are different measures. Alternative configurations, compound or repeated entries and partial stoplists can also differ. Read the labels and source attribution; an empty stoplist does not mean zero stops.'), compare, stopMatch);
  if (['history','activities'].includes(organTab)) return set('organ-history', 'History and participants', dates, eventMeaning, identity);
  if (organTab === 'media') return set('organ-media', 'Media and source access', media, item('media-subject', 'Does an image necessarily show the selected configuration?', 'Check its caption, source and any date. An image linked to an organ or venue may show an earlier configuration, another viewpoint or contextual material. The association alone does not date the technical details visible in it.'), citation);
  if (['export','identifiers'].includes(organTab)) return set('organ-export', 'Identifiers and exports', citation, item('rdf', 'Does valid RDF establish that every claim is historically correct?', 'RDF validation checks structure and identifiers. It can faithfully preserve uncertain, conflicting or imperfectly extracted source claims. Consult provenance, account qualifications and the original evidence when assessing historical accuracy.'), item('formats', 'Why do export profiles look different?', 'Profiles express the data using different schemas and conventions. Keep the selected dataset version and profile with your analysis. A change in representation does not itself provide additional independent evidence.'));
  return set('organ', 'Organ records', dates, missing, source, citation);
 }
 if (path === '/organs' || path === '/' || path === '/explore') return set('catalog', 'Finding organs', item('catalog-search', 'Why might an organ be missing from my results?', 'Check the active filters and search scope, then try another source spelling or the MODAVIS identifier. Source coverage and structured fields are uneven. To find organs by a stop name, use the stop terminology browser and inspect broader wording matches where needed.', '/vocab/usage/stops', 'Search recorded stop names'), source, missing);
 if (/^\/events(?:\/[^/]+)?$/.test(path)) return set('events', 'Events and participants', eventMeaning, identity, dates);
 if (path === '/map' || /^\/places(?:\/[^/]+)?$/.test(path) || /^\/entity\/places\/[^/]+$/.test(path)) return set('places', 'Places and maps', precision, item('map-history', 'Does a connecting line show an actual historical route?', 'A relocation connector relates documented endpoints. It is schematic and does not reconstruct a travelled route. The date, source and coordinate precision of each endpoint remain relevant.'), missing);
 if (/^\/(persons|people|organizations|actors|names)(?:\/[^/]+)?$/.test(path) || /^\/entity\/(people|organizations|institutions|buildings|source-actors)\/[^/]+$/.test(path)) return set('actors', 'People, organizations and names', identity, item('actor-scope', 'Does a name record represent a person?', 'A name, a source-specific actor mention and a canonical person or organization are different records. Follow the labelled relationships to see which identity is established. A workshop name may cover a different scope or period from an individual builder.'), network);
 if (/^\/virtual-instruments(?:\/[^/]+)?$/.test(path)) return set('virtual-instruments', 'Virtual instruments', item('virtual-link', 'Does a matching product or cathedral name prove an organ link?', 'No. An accepted link needs evidence identifying the represented instrument. Product name and town alone can be insufficient, especially after rebuilds or when several organs share a venue. Unresolved relationships remain explicitly qualified.'), item('virtual-state', 'Does a linked organ prove the sampled configuration?', 'The relationship identifies the represented organ where established. Check the provider’s description and configuration evidence for the sampled state, recording date and completeness. These do not follow automatically from the organ identity.'), item('virtual-filters', 'Why do the relationship filters change the results?', '“Linked to an organ record” selects accepted organ relationships. Distribution-related filters describe the virtual product and are a separate constraint. Review all active filters before interpreting an empty result.'));
 if (/^\/literature(?:\/[^/]+)?$/.test(path)) return set('literature', 'Literature and reading links', item('literature-access', 'Does a bibliographic record include a readable document?', 'A citation can be present without an accessible scan. Use the labelled public reading links where supplied; they may open an external viewer or document. Access can change at the source, and it does not itself establish reuse permission.'), item('literature-subject', 'Does a linked publication confirm every detail of this organ?', 'The relation supplies research context. Inspect the relevant passage, edition, page and date to determine which claim it supports. A publication reference alone is not evidence for every field on an organ page.'), citation);
 if (/^\/scores(?:\/[^/]+(?:\/assets\/[^/]+)?)?$/.test(path)) return set('scores', 'Scores and score assets', item('score-assets', 'Does a score record guarantee that an edition or scan is available?', 'The record describes the available catalogued evidence. Follow labelled reading or asset links and check the source, edition and access conditions; a metadata record alone does not establish access to the complete score.'), item('score-relation', 'Does an organ association prove where a work was performed?', 'Read the stated relationship and its source. Instrumentation, a dedication, a venue association and a documented performance are different claims. An association alone does not establish a particular performance or organ configuration.'), citation);
 if (/^\/temperaments(?:\/[^/]+)?$/.test(path)) return set('temperaments', 'Tuning systems', item('tuning-name', 'Do similar temperament names establish the same tuning?', 'Names and spelling variants support discovery. Check the retained wording and source details for modifications or a particular implementation. A label match alone does not establish identical intervals or a measured tuning.'), item('tuning-current', 'Does a recorded temperament establish the organ’s tuning today?', 'It is a source claim with its own context. Check the source date and any configuration or measurement evidence before treating it as a current observation.'), citation);
 if (/^\/source\/[^/]+$/.test(path)) return set('source', 'Source evidence', source, missing, citation);
 if (path === '/resources') return set('resources', 'Semantic resources and evidence', citation, item('resource-scope', 'Why does this resource have its own identifier?', 'An organ, a source account and a component can have different identifiers because they represent different subjects. Read the owner, resource type and provenance, then use the supplied links to return to the organ or account. A resource URL does not by itself establish a separate physical object.'), item('resource-validity', 'Does a valid semantic representation verify the source claim?', 'It verifies the representation’s structure. Historical accuracy, uncertainty and conflicting source evidence still require examination of the underlying claim and provenance. Select the stated dataset version and profile when comparing exports.'));
 if (path === '/about/release') return set('release', 'Dataset scope and citation', citation, source, missing);
 return null;
}
