import { JsonEvidence } from "./JsonEvidence";
import {useEffect,useState} from 'react';
import './researchWorkbench.css';
import {AppliedFilters,ResearchFilters} from './researchFilters';
import {CandidateConcepts} from './terminologyResearch';
import {AttributionNotes,OccurrenceFilters,OccurrenceResults} from './identityOccurrences';
type Row=Record<string,any>;
const enc=encodeURIComponent;
const PATH='/use-cases/research-workbench';
const pretty=(v:any)=>String(v??'Unspecified').replace(/_/g,' ');
function useQuery(url:string|null): {data?:Row,error?:string}{
 const [state,set]=useState<{url:string,data?:Row,error?:string}>();
 useEffect(()=>{if(!url)return;const c=new AbortController();fetch(url,{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Research evidence unavailable');return d;}).then(data=>set({url,data})).catch(e=>{if(!c.signal.aborted)set({url,error:e.message});});return()=>c.abort();},[url]);
 return state?.url===url?state:{};
}
function Evidence({value}:{value:any}){return <details><summary>Original evidence and identifiers</summary><JsonEvidence value={value} label="Original evidence and identifiers"/></details>;}
function Sources({value}:{value:Row}){const s=value.source;return <p className="wb-source">{s?.source_key||value.source_key||value.source_record_id||value.source||'Source unspecified'} {s?.source_url&&<a href={s.source_url} target="_blank" rel="noreferrer">Original source</a>}</p>;}
function Event({value}:{value:Row}){return <article className="wb-evidence"><a href={'/events/'+enc(value.event_id)}><strong>{pretty(value.controlled_event_type||value.source_event_type)}</strong></a><p>{value.dates?.map((x:Row)=>x.expression).filter(Boolean).join('; ')||'Undated'} · {value.source_only?'Source wording / contextual':'Controlled activity'}</p>{value.source_event_type&&<p>Source wording: {value.source_event_type}</p>}<Sources value={value}/>{value.narrative&&<details><summary>Event narrative</summary><p>{value.narrative}</p></details>}<ul>{value.participants?.map((p:Row,i:number)=><li key={i}>{p.targetId?<a href={'/people/'+enc(p.targetId.replace('MDVS:ENTY:',''))}>{p.wording}</a>:p.wording} · {pretty(p.role)}{!p.targetId&&' · Identity unresolved or unknown'}</li>)}</ul><Evidence value={value}/></article>;}
function AccountSummary({value}:{value:Row}){const scope=value.chronology?.sourceRelativeContext;return <><a href={value.href}><strong>{value.source_heading||value.period_label||'Source account'}</strong></a><p>{value.period_label} · {pretty(value.time_kind)} · {pretty(value.coverage)} · {pretty(value.subject_kind)} · {pretty(value.realization)}</p><Sources value={value}/>{scope&&<p>Account {scope.temporalRelation} {scope.boundaryYear}; this is a boundary, not an exact configuration year.</p>}{value.chronology?.sourceDateQualification&&<p>The account date and relative intervention are separate; the intervention date is not established.</p>}{value.chronology?.eventAssociations?.map((x:Row,i:number)=><p key={i}><a href={'/events/'+enc(x.eventId)}>{x.temporalRelation?`Account ${x.temporalRelation} this documented event`:'Related documented event'}</a> · Physical continuity and causation unestablished.</p>)}</>;}
function Stop({entry}:{entry:Row}){return <span>{entry.wording||entry.label||'Unlabelled entry'} · {entry.pitch||'Pitch unspecified'} · {entry.division||'Division unspecified'}</span>;}
function Pager({data,go,page}:{data:Row,go:(p:Row)=>void,page:number}){return <nav className="wb-pagination" aria-label="Workbench result pages"><button disabled={page===0} onClick={()=>go({page:page-1})}>Previous</button><span role="status">{data.total.toLocaleString()} results · {data.total?data.offset+1:0}–{Math.min(data.total,data.offset+data.items.length)}</span><button disabled={!data.hasMore} onClick={()=>go({page:page+1})}>Next</button></nav>;}
export function ResearchWorkbench(){
 const [search,setSearch]=useState(location.search);const params=new URLSearchParams(search);const mode=params.get('view')||'selection';
 const context=useQuery('/api/workbench/context');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [builderQuery,setBuilderQuery]=useState('');const builders=useQuery(builderQuery?'/api/research/actors?q='+enc(builderQuery):null);
 useEffect(()=>{const sync=()=>setSearch(location.search);window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync);},[]);
 function go(p:Row,reset=false){const n=reset?new URLSearchParams():new URLSearchParams(search);for(const [k,v] of Object.entries(p)){if(v===null||v===undefined||v==='')n.delete(k);else n.set(k,String(v));}const binding=context.data?.publicCoreSha256||result.data?.publicCoreSha256;if(binding)n.set('snapshot',binding);if(context.data?.occurrenceAssessmentSha256)n.set('assessment',context.data.occurrenceAssessmentSha256);const next=PATH+'?'+n.toString();history.pushState({},'',next);setSearch(location.search);setNotice('');}
 const section=params.get('section')||'events';const api=new URLSearchParams(params);api.delete('view');
 let url:string|null=null;
 if(mode==='selection'&&(params.get('actor')||params.get('organ')||params.get('source')||params.get('q')))url='/api/workbench/selection?'+api;
 if(mode==='compare'&&params.get('left')&&params.get('right'))url='/api/workbench/compare?'+api;
 if((mode==='timeline'||mode==='claims')&&params.get('organ'))url='/api/workbench/'+mode+'/'+enc(params.get('organ')!)+'?'+api;
 if(mode==='terms')url='/api/workbench/terms?'+api;
 if(mode==='occurrences')url='/api/workbench/occurrences?'+api;
 if(mode==='identities')url='/api/workbench/identities?'+api;
 const result=useQuery(url);const data=result.data;const facets=context.data?.facets;
 useEffect(()=>{document.title='Organological research workbench | MODAVIS Navigator';},[]);
 useEffect(()=>{if(!context.data)return;const n=new URLSearchParams(search);let changed=false;if(!n.get('snapshot')){n.set('snapshot',context.data.publicCoreSha256);changed=true;}if(context.data.occurrenceAssessmentSha256&&!n.get('assessment')){n.set('assessment',context.data.occurrenceAssessmentSha256);changed=true;}if(mode==='compare'&&data?.left&&data?.right){for(const side of ['left','right'])if(!n.get(side+'Revision')){n.set(side+'Revision',data[side].metadata.description_revision);changed=true;}}if(changed){history.replaceState({},'',PATH+'?'+n);setSearch(location.search);}},[context.data,data,mode,search]);
 const snapshotMismatch=!!(params.get('snapshot')&&context.data&&params.get('snapshot')!==context.data.publicCoreSha256);
 function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget).entries());go({...values,view:mode,page:0},true);}
 function selectAccount(id:string,revision:string){const existing=params.get('left');if(!existing)go({left:id,leftRevision:revision});else if(existing===id)go({left:null,leftRevision:null});else go({right:id,rightRevision:revision,view:'compare'});}
 async function download(format:string){setBusy(true);setNotice('');try{const r=await fetch('/api/workbench/selection/export?'+api+'&format='+format);if(!r.ok){const d=await r.json();throw new Error(d.error);}const blob=await r.blob();const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download='modavis-research.'+format;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);setNotice('Complete filtered selection downloaded.');}catch(e){setNotice(String(e));}finally{setBusy(false);}}
 return <section className="research-workbench story-page" aria-label="Organological research workbench"><a href="/use-cases">← All research use cases</a><header className="story-hero"><p className="eyebrow">Organological research</p><h1>Research workbench</h1><p>Ask a question, compare the source accounts, and retain the exact evidence behind your result.</p></header>
 <nav className="wb-tabs" aria-label="Research workbench views">{[['selection','Build a selection'],['compare','Compare accounts'],['timeline','Qualified timeline'],['terms','Terminology'],['claims','Compare sources'],['identities','Identity research'],['occurrences','Attribution evidence']].map(([key,label])=><button key={key} aria-pressed={mode===key} onClick={()=>go({view:key,page:0})}>{label}</button>)}</nav>
 {context.error&&<p role="alert">{context.error}</p>}{snapshotMismatch&&<p role="alert">This link belongs to a different data snapshot. Its results cannot be reproduced against this candidate.</p>}
 <details className="wb-help wb-starters"><summary>Start with a research question</summary><div className="wb-templates"><button onClick={()=>go({view:'selection',actor:'W8AZ-2EJP-P',section:'events'},true)}>Möller: documented interventions</button><button onClick={()=>go({view:'selection',organ:'EAXV-HAAS-S',section:'configurations'},true)}>Enschede: compare configuration accounts</button><button onClick={()=>go({view:'timeline',organ:'031M-S34V-V'},true)}>Pels: construction, transfer and restoration</button><button onClick={()=>go({view:'terms',mode:'stops',q:'Principal'},true)}>Principal: wording and source distributions</button><button onClick={()=>go({view:'claims',organ:'FFH7-Z9KV-V'},true)}>Frauenthal: separately attributed claims</button><button onClick={()=>go({view:'identities'},true)}>People, workshops and generations</button></div></details>
 {(mode==='selection')&&<details className="wb-builder-search"><summary>Find a builder or organization</summary><label>Builder name<input value={builderQuery} onChange={e=>setBuilderQuery(e.target.value)} placeholder="Möller, Schuke…"/></label>{builders.error&&<p role="alert">{builders.error}</p>}<div className="wb-builder-results">{builders.data?.items?.map((x:Row)=><button key={x.id} onClick={()=>go({actor:x.id,section:'events',page:0})}>{x.label} · {x.organ_count.toLocaleString()} organs</button>)}</div></details>}
 {!['identities','occurrences'].includes(mode)&&<ResearchFilters params={params} mode={mode} facets={facets} onSubmit={submit}/>}
 {mode==='occurrences'&&<OccurrenceFilters params={params} data={data} go={go}/>}
 <AppliedFilters params={params} mode={mode} go={go}/>
 <p className="wb-context">{mode==='occurrences'?'Each assessment tests a retained attribution against its source evidence. A compatible date does not prove identity; a workshop replacement is never inferred. Records outside this bounded cohort remain unassessed.':'Year filters use reported event start years or year/century accounts. Relative, undated and source-listing configurations remain available when no year filter is applied. Source country describes a current listing location.'}</p>
 <div className="wb-tools"><button onClick={async()=>{try{await navigator.clipboard.writeText(location.href);setNotice('Research link copied.');}catch{setNotice('Copy the address from your browser to retain this selection.');}}}>Copy research link</button><a href={PATH+search}>Permanent selection URL</a>{mode==='selection'&&data&&<><button disabled={busy} onClick={()=>download('json')}>Download complete selection · JSON</button><button disabled={busy} onClick={()=>download('csv')}>Download complete selection · CSV</button></>}</div>{notice&&<p role="status">{notice}</p>}
 {result.error&&<p role="alert">{result.error}</p>}{url&&!data&&!result.error&&<p role="status">Loading research evidence…</p>}
 {!url&&mode==='selection'&&<div className="wb-empty"><h2>Your research starts here</h2><p>Choose a research question above, find a builder, or enter an organ name to bring the evidence into view.</p></div>}
 {data&&!snapshotMismatch&&<>
 {data.identityFilterMethod&&<p className="wb-method">{data.identityFilterMethod}</p>}
 {data.method&&<p className="wb-method">{data.method}</p>}
 {mode==='occurrences'&&<><Pager data={data} go={go} page={Number(params.get('page')||0)}/><OccurrenceResults data={data}/><Pager data={data} go={go} page={Number(params.get('page')||0)}/><a href={'/api/workbench/occurrences/export?'+api} download="modavis-identity-occurrences.json">Download complete attribution selection · JSON</a></>}

 {mode==='selection'&&<>{data.identityAssessments?.length>0&&<details open><summary>Identity evidence affects this selection</summary>{data.identityAssessments.map((g:Row)=><p key={g.nativeId}><strong>{g.sourceNames.join(' / ')}:</strong> {g.remaining}</p>)}<button onClick={()=>go({view:'identities'})}>Inspect the identity research and primary sources</button></details>}<Pager data={data} go={go} page={Number(params.get('page')||0)}/>{params.get('left')&&<p role="status">First account selected: {params.get('left')}. Select a second account.</p>}<div className="wb-results">{data.items.map((x:Row,i:number)=><article key={x.id+':'+i}><h2><a href={x.organHref}>{x.label}</a></h2>{section==='events'?<Event value={x.evidence}/>:section==='sequences'?<div className="wb-columns"><Event value={x.evidence}/><Event value={x.later}/></div>:section==='configurations'?<><AccountSummary value={{...x.evidence,href:x.href}}/><button onClick={()=>selectAccount(x.id,x.evidence.description_revision)}>{params.get('left')===x.id?'Remove first account':'Select for comparison'}</button></>:<><p>{x.sources.length} source records; independence unestablished.</p><Evidence value={x.sources}/></>}{['events','sequences'].includes(section)&&<AttributionNotes items={[...(x.identityOccurrences||[]),...(x.laterIdentityOccurrences||[])]} inspect={v=>go(v,true)}/>}<div className="wb-tools"><button onClick={()=>go({view:'timeline',organ:x.organ},true)}>Read qualified timeline</button><button onClick={()=>go({view:'claims',organ:x.organ},true)}>Compare source claims</button><button onClick={()=>go({view:'selection',section:'configurations',organ:x.organ},true)}>Inspect configuration accounts</button></div></article>)}</div><details><summary>Citation and selection identity</summary><p>MODAVIS Navigator research selection {data.selectionSha256}, candidate core {data.publicCoreSha256}. Filters: {JSON.stringify(data.filters)}. Use the release context and core checksum to identify this preparation; publication status is recorded separately.</p></details></>}
 {mode==='compare'&&<><div className="wb-columns">{['left','right'].map(side=><article key={side}><h2>{side==='left'?'First account':'Second account'}</h2><AccountSummary value={{...data[side].metadata,href:data[side].href}}/><p>Revision: {data[side].metadata.description_revision}</p></article>)}</div><p className="wb-method">{data.comparison.method}</p><div className="wb-stats"><span>{data.comparison.both.length} matching entry pairs</span><span>{data.comparison.leftOnly.length} only in first account</span><span>{data.comparison.rightOnly.length} only in second account</span><span>{data.comparison.ambiguous.length} ambiguous groups</span></div><details open><summary>Matching recorded entries</summary><ul>{data.comparison.both.map((x:Row,i:number)=><li key={i}><Stop entry={x.left}/> ↔ <Stop entry={x.right}/></li>)}</ul></details><div className="wb-columns">{['leftOnly','rightOnly'].map((key,i)=><details key={key} open><summary>Only documented in {i===0?'first':'second'} account</summary><ul>{data.comparison[key].map((x:Row,j:number)=><li key={j}><Stop entry={x}/></li>)}</ul></details>)}</div><details><summary>Uncertain correspondences</summary>{data.comparison.ambiguous.map((x:Row,i:number)=><div key={i}><p>{x.reason}</p><Evidence value={x}/></div>)}</details><a href={'/api/workbench/compare?'+api} download="modavis-account-comparison.json">Download comparison evidence</a></>}
 {mode==='timeline'&&<><h2>Documented events and qualified accounts</h2><div className="wb-columns"><section><h3>{data.events.length} event assertions</h3>{data.events.map((x:Row)=><Event key={x.event_id} value={x}/>)}</section><section><h3>{data.accounts.length} separate configuration accounts</h3>{data.accounts.map((x:Row)=><article key={x.description_id}><AccountSummary value={x}/><button onClick={()=>go({view:'selection',section:'configurations',organ:data.organId},true)}>Compare this organ’s accounts</button></article>)}</section></div><a href={url||''} download="modavis-timeline.json">Download timeline evidence</a></>}
 {mode==='claims'&&<><h2>{data.sources.length} separately attributed source records</h2><p>Independent corroboration has not been established. Existing organ membership is retained.</p><div className="wb-columns">{data.sources.map((x:Row)=><article key={x.source_record_id}><h3>{x.source_key}</h3><a href={x.source_url} target="_blank" rel="noreferrer">Original source</a><p>{x.native_identifier}</p><details><summary>Source revision and membership</summary><Evidence value={x}/></details></article>)}</div><h2>Reported technical values</h2>{data.technicalClaims.length===0&&<p>No retained aggregate technical assertions for this organ.</p>}{data.technicalClaims.map((g:Row)=><article key={g.family}><h3>{pretty(g.family)}</h3><p>{g.comparison}</p><div className="wb-table"><table><thead><tr><th>Source</th><th>Reported value</th><th>Support / conflict</th><th>Evidence</th></tr></thead><tbody>{g.assertions.map((x:Row)=><tr key={x.fact_id}><td>{x.source_record_id}</td><td>{x.display_value}</td><td>{pretty(x.support_state)} · {pretty(x.conflict_state)}</td><td><Evidence value={x}/></td></tr>)}</tbody></table></div></article>)}<details><summary>Builder assertions · {data.builderClaims.length}</summary>{data.builderClaims.map((x:Row)=><article key={x.assertion_id}><strong>{x.source_label}</strong><p>{x.source_record_id} · {x.relation_role} · {x.actor_mdvs_id||'Identity unresolved'}</p><Evidence value={x}/></article>)}</details><details><summary>Configuration accounts · {data.accounts.length}</summary>{data.accounts.map((x:Row)=><article key={x.description_id}><AccountSummary value={x}/></article>)}</details><details><summary>Event assertions · {data.events.length}</summary>{data.events.map((x:Row)=><Event key={x.event_id} value={x}/>)}</details><a href={url||''} download="modavis-source-comparison.json">Download all attributed claims</a></>}
 {mode==='terms'&&<><CandidateConcepts concepts={data.candidateConcepts||[]} go={go}/><a href={'/api/workbench/terms/export?'+api} download="modavis-terminology-selection.json">Download complete terminology selection · JSON</a><div className="wb-stats"><span>{data.total.toLocaleString()} matching occurrences</span><span>{data.denominator.occurrences.toLocaleString()} occurrences in selected coverage</span><span>{data.denominator.sourceRecords.toLocaleString()} source records</span><span>{data.denominator.organs.toLocaleString()} organs</span></div><details><summary>Controlled vocabulary definitions and retained mappings · {data.concepts.length}</summary>{data.concepts.map((x:Row)=><article key={x.code}><a href={'/vocab/'+enc(x.scheme?.code||'modavis_activity_types')+'/concepts/'+enc(x.code)}><h3>{x.preferredLabel}</h3></a><p>{x.definition}</p><p>{x.labels?.map((l:Row)=>`${l.label} (${l.languageCode||'unspecified language'})`).join(' · ')}</p>{x.scheme?.code==='modavis_activity_types'&&<button onClick={()=>go({mode:'activities',q:null,concept:x.code,page:0})}>Inspect retained occurrences</button>}<Evidence value={x}/></article>)}</details><Pager data={data} go={go} page={Number(params.get('page')||0)}/><div className="wb-table"><table><thead><tr><th>Source wording</th><th>Pitch / division</th><th>Source and country</th><th>Account date</th><th>Mapping</th></tr></thead><tbody>{data.items.map((x:Row,i:number)=><tr key={x.id+':'+i}><td><a href={x.href}>{x.label}</a></td><td>{x.pitch||'Unspecified'} · {x.division||'Unspecified'}</td><td>{x.source_key} · {x.country||'Unassigned'}</td><td>{x.year??'Unestablished'} · {pretty(x.date_kind)}</td><td>{x.conceptHref?<a href={x.conceptHref}>{x.concept}</a>:x.terminologyMapping?.status==='accepted_lexical_mapping'?<><strong>Candidate concept</strong><p>Accepted lexical mapping</p><code>{x.concept}</code></>:'Unmapped source wording'}<Evidence value={x}/></td></tr>)}</tbody></table></div></>}
 {mode==='identities'&&<><p>{data.method}</p><p>All {data.coverage.competingNativeIdentifiers} competing native-ID groups are retained with explicit decisions, plus the Friese generation case. No canonical identities or source memberships were changed.</p>{data.groups.map((g:Row)=><article key={g.nativeId}><h2>{g.sourceNames.join(' / ')} <small>Orgbase {g.nativeId}</small></h2><button onClick={()=>go({view:'occurrences',native:g.nativeId},true)}>Inspect individual attributions</button><p>{g.finding}</p><p><strong>Established:</strong> {g.resolved}</p><p><strong>Still unresolved:</strong> {g.remaining}</p>{g.authorityProfile&&<details><summary>Inspected authority profile and naming evidence</summary><p>{g.authorityProfile.preferredName} · {g.authorityProfile.variantName?.join(' · ')}</p><p>{g.authorityProfile.dateOfBirth?.join('; ')} – {g.authorityProfile.dateOfDeath?.join('; ')}</p><p>{g.authorityProfile.professionOrOccupation?.map((x:Row)=>x.label).join(' · ')}</p><p>{g.authorityProfile.biographicalOrHistoricalInformation?.join('; ')}</p>{g.authorityDateConflicts?.length>0&&<p role="note">The retained actor dates and authority dates disagree. Revalidation is required before this authority can anchor a new match.</p>}<Evidence value={g.authorityDateConflicts}/></details>}<ul>{g.actors.map((a:Row)=><li key={a.mdvs_id}><a href={'/people/'+enc(a.mdvs_id.replace('MDVS:ENTY:',''))}>{a.label}</a> · {a.actor_type}<Evidence value={a}/></li>)}</ul>{g.evidence.map((e:Row,i:number)=><div key={i}><a href={e.url} target="_blank" rel="noreferrer">{e.sourceId}: primary evidence</a>{e.excerpt&&<blockquote>{e.excerpt}</blockquote>}<p className="wb-source">Retrieved {e.retrievedAt} · SHA-256 {e.sha256}</p></div>)}</article>)}<a href={url||''} download="modavis-identity-assessments.json">Download identity research</a></>}
 </>}
 <details className="wb-help"><summary>Snapshot and research boundaries</summary><p>The workbench reads a frozen public core. Its analysis does not alter canonical identities, add sources to organs, or establish physical continuity. Independent corroboration and historical causation require further evidence.</p>{context.data&&<p>Core SHA-256: {context.data.publicCoreSha256}</p>}<p>Full selection exports support up to {context.data?.exportLimit?.toLocaleString()||'50,000'} records. Larger requests fail explicitly and can be narrowed; no partial export is presented as complete.</p></details>
 </section>;
}
