import {useEffect,useState} from 'react';
import {JsonEvidence} from './JsonEvidence';
import './researchExploration.css';
type Row=Record<string,any>;
const n=(v:number)=>v.toLocaleString();
const dims:Record<string,string>={source:'Source collection',country:'Source-listed country',period:'Qualified period',pitch:'Recorded pitch',division:'Recorded division'};
function useData(url:string):{data?:Row,error?:string}{const [state,set]=useState<{url:string,data?:Row,error?:string}>();useEffect(()=>{if(!url)return;const controller=new AbortController();fetch(url,{signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Research unavailable');if(!controller.signal.aborted)set({url,data:d})}).catch(e=>{if(!controller.signal.aborted)set({url,error:e.message})});return()=>controller.abort()},[url]);return state?.url===url?state:{};}
function Pager({data,go}:{data:Row,go:(page:number)=>void}){return <nav className="rx-pager" aria-label="Analysis result pages"><button disabled={!data.offset} onClick={()=>go(Math.max(0,Math.floor(data.offset/(data.focus?8:15))-1))}>Previous</button><span>{data.total?data.offset+1:0}–{Math.min(data.total,data.offset+data.items.length)} of {n(data.total)} {data.focus?'connections':'groups'}</span><button disabled={!data.hasMore} onClick={()=>go(Math.floor(data.offset/(data.focus?8:15))+1)}>Next</button></nav>}
export function TermDistribution({family,search,go}:{family:string,search:string,go:(values:Row)=>void}){
 const p=new URLSearchParams(search);const open=p.get('view')==='distribution';const dimension=p.get('groupBy')||'source';const [metric,setMetric]=useState('occurrences');
 const q=new URLSearchParams({term:p.get('term')||'',match:p.get('match')||'exact',dimension,page:p.get('distributionPage')||'0',zeros:p.get('zeros')||'no'});
 for(const key of ['source','snapshot','analysis'])if(p.get(key))q.set(key,p.get(key)!);
 const api='/api/research-exploration/terms/'+family+'?'+q;const {data,error}=useData(open?api:'');
 useEffect(()=>{if(open&&data&&!p.has('analysis')){const next=new URLSearchParams(location.search);next.set('analysis',data.analysisSha256);history.replaceState({},'',location.pathname+'?'+next);window.dispatchEvent(new PopStateEvent('popstate'))}},[data]);
 const max=data?Math.max(1,...data.items.map((r:Row)=>metric==='occurrences'?r.matches.occurrences:r.accountPercent||0)):1;
 return <section className="rx-section" aria-label="Term distributions"><div className="rx-section-head"><div><p className="eyebrow">Research this wording</p><h3>Distribution and documentation coverage</h3></div><button aria-expanded={open} onClick={()=>go({view:open?null:'distribution',distributionPage:0})}>{open?'Hide distributions':'Explore distributions'}</button></div>
 {open&&<><p>Compare recorded usage within each source, location or specification context. These are distributions of documentation, not estimates of the historical organ population.</p>{p.get('bucket')&&<p role="note">This chart covers the selected wording and source across all groups. The occurrence list below is narrowed to your selected group.</p>}
 <div className="rx-controls"><label>Group by<select aria-label="Distribution group" value={dimension} onChange={e=>go({groupBy:e.target.value,distributionPage:0})}>{Object.entries(dims).filter(([k])=>family!=='activities'||!['pitch','division'].includes(k)).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Measure<select aria-label="Distribution measure" value={metric} onChange={e=>setMetric(e.target.value)}><option value="occurrences">Matching occurrences</option><option value="accounts">Share of documented {family==='activities'?'events':'accounts'}</option></select></label><label className="rx-check"><input type="checkbox" checked={p.get('zeros')==='yes'} onChange={e=>go({zeros:e.target.checked?'yes':'no',distributionPage:0})}/>Include groups with no matches</label></div>
 {error&&<p role="alert">{error}</p>}{!data&&!error&&<p role="status">Loading distribution…</p>}{data&&<><div className="rx-summary"><strong>{n(data.matchingOccurrences)} matching occurrences</strong><span>Coverage before term matching: {n(data.coverage.occurrences)} occurrences · {n(family==='activities'?data.coverage.records:data.coverage.accounts)} {data.unit} · {n(data.coverage.organs)} organs</span></div>
 <p className="rx-method">{dimension==='period'?'Only dates recorded as a single established year enter 50-year periods. Intervals, source listings and undated accounts remain separate.':dimension==='country'?'Countries come from source-listed locations; they do not establish the historical location of an event or configuration.':dimension==='pitch'||dimension==='division'?'Pitch and division labels remain literal source wording. Similar spellings are not automatically equivalent.':'Collections can repeat or depend on other sources; separate records do not establish independent corroboration.'} {metric==='accounts'?`Each percentage compares matching ${family==='activities'?'events':'accounts'} with all documented ${family==='activities'?'events':'accounts containing recorded '+family+' entries'} in that group.`:'Bars count source occurrences; several may belong to one account or organ.'} Accounts may be partial, and the same account or organ can occur in multiple groups.</p>
 <Pager data={data} go={page=>go({distributionPage:page})}/><div className="rx-bars" aria-label="Distribution chart">{data.items.map((r:Row)=><div className="rx-bar-row" key={r.bucket}><div><a href={r.href}>{r.label}</a><strong>{metric==='occurrences'?n(r.matches.occurrences):(r.accountPercent===null?'Unestablished':r.accountPercent.toFixed(2)+'%')}</strong></div><div className="rx-bar-track" aria-hidden="true"><span style={{width:(100*(metric==='occurrences'?r.matches.occurrences:r.accountPercent||0)/max)+'%'}}/></div></div>)}</div>
 {!data.total&&<p>No matching groups. Include groups with no matches to inspect available coverage.</p>}
 <details className="rx-table-detail" open><summary>Underlying counts and source evidence</summary><div className="rx-table"><table><thead><tr><th>{dims[dimension]}</th><th>Matching / recorded occurrences</th><th>Matching / recorded {family==='activities'?'events':'accounts'}</th><th>Matching / documented organs</th><th>Evidence</th></tr></thead><tbody>{data.items.map((r:Row)=><tr key={r.bucket}><th scope="row">{r.label}</th><td>{n(r.matches.occurrences)} / {n(r.coverage.occurrences)}</td><td>{n(family==='activities'?r.matches.records:r.matches.accounts)} / {n(family==='activities'?r.coverage.records:r.coverage.accounts)}</td><td>{n(r.matches.organs)} / {n(r.coverage.organs)}</td><td>{r.matches.occurrences?<a href={r.href}>Inspect occurrences</a>:'No recorded matches'}</td></tr>)}</tbody></table></div></details>
 <div className="rx-links"><a href={api.replace('?','/export?')+'&format=csv'} download>Download complete chart table · CSV</a><a href={api.replace('?','/export?')} download>Download complete analysis and methods · JSON</a></div><p>Downloads include all groups in this selection, independently of the displayed page. Zero means no matching documentation in that group; it does not establish historical absence.</p><details><summary>Method and reproducible analysis identity</summary><p>{data.method}</p><JsonEvidence value={{selection:data.selection,selectionSha256:data.selectionSha256,publicCoreSha256:data.publicCoreSha256,analysisSha256:data.analysisSha256,policySha256:data.policySha256,querySha256:data.querySha256}} label="Distribution citation"/></details></>}
 </>}
 </section>
}
const modes:Record<string,string>={shared:'Shared organs',joint:'Joint event participation',later:'Later work by connected actors',earlier:'Earlier work by connected actors'};
export function BuilderNetwork({actor,onChoose}:{actor:string,onChoose:(id:string)=>void}){
 const [search,setSearch]=useState(location.search);useEffect(()=>{const fn=()=>setSearch(location.search);window.addEventListener('popstate',fn);return()=>window.removeEventListener('popstate',fn)},[]);
 const p=new URLSearchParams(search);const open=p.get('network')==='yes';const mode=p.get('networkMode')||'shared';const [selected,setSelected]=useState<string>();const [notice,setNotice]=useState('');
 function go(values:Row,replace=false){const next=new URLSearchParams(location.search);next.set('actor',actor);for(const [k,v] of Object.entries(values)){if(v===null)next.delete(k);else next.set(k,String(v))}history[replace?'replaceState':'pushState']({},'',location.pathname+'?'+next);window.dispatchEvent(new PopStateEvent('popstate'));setSelected(undefined)}
 const q=new URLSearchParams({actor,mode,page:p.get('networkPage')||'0'});for(const k of ['snapshot','assessment'])if(p.get(k))q.set(k,p.get(k)!);
 const api='/api/research-exploration/network?'+q;const {data,error}=useData(open?api:'');
 useEffect(()=>{if(data&&(!p.get('snapshot')||!p.get('assessment')))go({snapshot:data.publicCoreSha256,assessment:data.identityEvidenceSha256},true)},[data]);
 useEffect(()=>{setSelected(undefined)},[actor,mode]);
 const peer=data?.items.find((r:Row)=>r.id===selected);const unit=mode==='shared'?'shared organs':mode==='joint'?'joint event assertions':'ordered event-assertion pairs';
 return <section className="rx-section" aria-label="Interactive builder network"><div className="rx-section-head"><div><p className="eyebrow">Explore the connections</p><h3>Interactive builder network</h3></div><button aria-expanded={open} onClick={()=>go({network:open?'no':'yes',networkPage:0})}>{open?'Hide network':'Show interactive network'}</button></div>
 {open&&<><div className="rx-controls"><label>Connection type<select aria-label="Network connection type" value={mode} onChange={e=>go({networkMode:e.target.value,networkPage:0})}>{Object.entries(modes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><button onClick={async()=>{try{await navigator.clipboard.writeText(location.href);setNotice('Network link copied.')}catch{setNotice('Copy this page URL to retain the network selection.')}}}>Copy network link</button></div>{notice&&<p role="status">{notice}</p>}
 <p className="rx-method">{mode==='shared'?'Connections count distinct organs associated with both actors. They do not establish that the actors worked together.':mode==='joint'?'Connections count controlled source event assertions naming both actors. Repeated assertions can describe the same historical event.':'Arrows run from earlier to later documented work on the same organ, using strictly non-overlapping bounded event dates. Actors jointly present in either event are excluded.'} No connection establishes apprenticeship, family ties, company succession or continuity of physical fabric. Counts include unresolved and unassessed attributions.</p>
 {error&&<p role="alert">{error}</p>}{!data&&!error&&<p role="status">Loading connections…</p>}{data&&<>{data.focus.identityNotes.length>0&&<p className="rx-warning">The focal actor has unresolved identity evidence. <a href={'/use-cases/research-workbench?view=occurrences&actor='+encodeURIComponent(actor)}>Inspect individual attributions</a> before interpreting these connections.</p>}
 <Pager data={data} go={page=>go({networkPage:page})}/><p>Showing {data.items.length} of {n(data.total)} connected actors, ordered by {unit}. This is a focal network; connections between the surrounding actors are not shown.</p>
 {data.items.length>0&&<svg className="rx-network" viewBox="0 0 800 530" role="group" aria-label="Focal builder network; select an actor to inspect its connection"><defs><marker id="rx-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#60766d"/></marker></defs>{data.items.map((r:Row,i:number)=>{const angle=2*Math.PI*i/data.items.length-Math.PI/2;const x=400+300*Math.cos(angle),y=265+200*Math.sin(angle);const dx=x-400,dy=y-265,length=Math.hypot(dx,dy);const a={x:400+dx/length*62,y:265+dy/length*62},b={x:x-dx/length*35,y:y-dy/length*35};return <g key={r.id}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="#60766d" strokeWidth={2+Math.min(5,Math.log10(r.weight+1))} markerEnd={mode==='later'?'url(#rx-arrow)':undefined} markerStart={mode==='earlier'?'url(#rx-arrow)':undefined}/><rect x={(x+400)/2-22} y={(y+265)/2-12} width="44" height="22" rx="5" fill="#f5f6ef"/><text x={(x+400)/2} y={(y+265)/2+4} textAnchor="middle" className="rx-edge-count">{n(r.weight)}</text><g role="button" tabIndex={0} aria-label={r.label+': '+n(r.weight)+' '+unit} aria-pressed={selected===r.id} onClick={()=>setSelected(r.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(r.id)}}}><title>{r.label}</title><circle cx={x} cy={y} r="31" className={selected===r.id?'rx-node selected':'rx-node'}/><text x={x} y={y+5} textAnchor="middle" className="rx-node-initial">{r.label.slice(0,2)}</text><text x={x} y={y+(y<265?-43:50)} textAnchor="middle" className="rx-node-label">{r.label.length>26?r.label.slice(0,24)+'…':r.label}</text></g></g>})}<circle cx="400" cy="265" r="60" fill="#193f34"/><text x="400" y="260" textAnchor="middle" fill="white" className="rx-focus-label" textLength={data.focus.label.length>16?108:undefined} lengthAdjust="spacingAndGlyphs"><title>{data.focus.label}</title>{data.focus.label.slice(0,23)}</text><text x="400" y="281" textAnchor="middle" fill="#e0cd97" fontSize="13">Focal actor</text></svg>}
 {peer&&<article className="rx-peer" aria-live="polite"><h4><a href={peer.href}>{peer.label}</a></h4><p>{n(peer.weight)} {unit}{peer.organs!==undefined&&<> on {n(peer.organs)} organs</>}. {peer.directed&&<>Direction: {mode==='earlier'?peer.label:data.focus.label} → {mode==='earlier'?data.focus.label:peer.label}.</>}</p>{(peer.audit||peer.identityNotes.length>0)&&<p className="rx-warning">Identity correspondence or attribution remains unresolved. <a href={'/use-cases/research-workbench?view=occurrences&actor='+encodeURIComponent(peer.id)}>Inspect attribution evidence</a>.</p>}<div className="rx-links"><a href={peer.evidenceHref}>Inspect supporting records</a><button onClick={()=>onChoose(peer.id)}>Explore this actor’s network</button></div>{peer.identityNotes.map((x:Row)=><p key={x.cohort}>{x.remaining}</p>)}</article>}
 <div className="rx-table"><table><caption>Accessible connection list — the same connections as the diagram</caption><thead><tr><th>Connected actor</th><th>{unit}</th><th>Evidence</th><th>Explore</th></tr></thead><tbody>{data.items.map((r:Row)=><tr key={r.id}><th scope="row"><button className="rx-text-button" onClick={()=>setSelected(r.id)}>{r.label}</button>{(r.audit||r.identityNotes.length>0)&&<small>Identity evidence unresolved</small>}</th><td>{n(r.weight)}</td><td><a href={r.evidenceHref}>Supporting records</a></td><td><button onClick={()=>onChoose(r.id)}>Make focal actor</button></td></tr>)}</tbody></table></div>{!data.total&&<p>No qualifying connections for this layer. This does not establish that historical connections did not exist.</p>}
 <div className="rx-links"><a href={api.replace('?','/export?')} download>Download all connections in this layer · JSON</a><a href={'/use-cases/research-workbench?view=occurrences&actor='+encodeURIComponent(actor)}>Review attribution evidence</a></div><details><summary>Network method and reproducible selection</summary><p>{data.method}</p><JsonEvidence value={{actor:data.focus.id,mode:data.mode,selectionSha256:data.selectionSha256,publicCoreSha256:data.publicCoreSha256,connectionIndexSha256:data.connectionIndexSha256,identityEvidenceSha256:data.identityEvidenceSha256,querySha256:data.querySha256}} label="Network citation"/></details>
 </>}
 </>}
 </section>
}
