import {TermDistribution} from './researchExploration';
import {useEffect,useState} from 'react';
import {ArrowRight,Search,Copy,Download} from 'lucide-react';
import {JsonEvidence} from './JsonEvidence';
import './vocabularyHub.css';
type Row=Record<string,any>;
const families:Record<string,string>={activities:'Events and activities',stops:'Stops',divisions:'Divisions'};
function useData(url:string):{data?:Row,error?:string}{const [state,set]=useState<{url:string,data?:Row,error?:string}>();useEffect(()=>{if(!url)return;const c=new AbortController();fetch(url,{signal:c.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error||'Vocabulary unavailable');set({url,data});}).catch(e=>{if(!c.signal.aborted)set({url,error:e.message})});return()=>c.abort()},[url]);return state?.url===url?state:{};}
const n=(x:number)=>x.toLocaleString();
const usageLink=(family:string,term?:string)=>'/vocab/usage/'+family+(term?'?'+new URLSearchParams({term}):'');
function Evidence({value}:{value:unknown}){return <details><summary>Original evidence and identifiers</summary><JsonEvidence value={value}/></details>}
function UsageSearch({family,q}:{family:string,q:string}){const {data,error}=useData('/api/vocab/usage/'+family+'?'+new URLSearchParams({q}));return <section className="vh-search-group"><h3>{families[family]} · source wording</h3>{error?<p role="alert">{error}</p>:!data?<p role="status">Searching source wording…</p>:<><p>{n(data.total)} distinct wordings</p>{data.items.slice(0,5).map((x:Row)=><p key={x.key}><a href={x.href}>{x.label}</a> <small>{n(x.occurrences)} occurrences</small></p>)}<a href={'/vocab/usage/'+family+'?'+new URLSearchParams({q})}>Browse matching wordings <ArrowRight size={14}/></a></>}</section>}
export function VocabularyHub(){const [q,setQ]=useState(new URLSearchParams(location.search).get('q')||'');const [input,setInput]=useState(q);const concepts=useData(q?'/api/vocab/concepts?'+new URLSearchParams({q,limit:'100'}):'');const omaro=useData(q?'/api/omaro/concepts?'+new URLSearchParams({q,resolution:'resolved',limit:'5'}):'');const schemes=useData('/api/vocab/schemes');const releases=useData('/api/vocab/releases?limit=12');
 useEffect(()=>{const fn=()=>{const value=new URLSearchParams(location.search).get('q')||'';setQ(value);setInput(value)};window.addEventListener('popstate',fn);return()=>window.removeEventListener('popstate',fn)},[]);
 const submit=(e:React.FormEvent)=>{e.preventDefault();const value=input.trim();history.pushState({},'','/vocab'+(value?'?'+new URLSearchParams({q:value}):''));setQ(value)};
 return <section className="vh-page" aria-label="Vocabulary and source terminology"><header className="vh-hero"><p className="eyebrow">MODAVIS vocabularies</p><h2>Explore terms and their evidence</h2><p>Find definitions, follow recorded wording, and discover the organs, events and specification accounts connected to a term.</p><form className="vh-search" onSubmit={submit}><label><span>Search terms across collections</span><input value={input} onChange={e=>setInput(e.target.value)} maxLength={200} placeholder="Dankesbrief, Vox Humana, repair…"/></label><button type="submit"><Search size={16}/>Search</button>{q&&<a href="/vocab">Clear</a>}</form></header>
 {q&&<section aria-label="Term search results"><h3>Results for “{q}”</h3><div className="vh-grid"><section className="vh-search-group"><h3>Controlled concepts</h3>{concepts.error?<p role="alert">{concepts.error}</p>:!concepts.data?<p role="status">Searching concepts…</p>:<><p>{n(concepts.data.total)} matching concepts</p>{concepts.data.items.map((x:Row)=><p key={x.code}><a href={'/vocab/'+encodeURIComponent(x.scheme?.code||'modavis_activity_types')+'/concepts/'+encodeURIComponent(x.code)}>{x.preferredLabel||x.code}</a>{x.definition&&<small>{x.definition}</small>}</p>)}</>}</section>{Object.keys(families).map(f=><UsageSearch key={f+q} family={f} q={q}/>)}<section className="vh-search-group"><h3>OMARO instrument concepts</h3>{omaro.error?<p role="alert">{omaro.error}</p>:!omaro.data?<p role="status">Searching reference concepts…</p>:<><p>{n(omaro.data.total)} matching source concepts</p>{omaro.data.items.map((x:Row)=><p key={x.uri}><a href={'/vocab/omaro?'+new URLSearchParams({uri:x.uri,snapshot:omaro.data!.snapshotSha256})}>{x.label}</a></p>)}<a href={'/vocab/omaro?'+new URLSearchParams({q})}>Browse OMARO matches</a></>}</section></div></section>}
 <div className="vh-grid" aria-label="Terminology collections"><article><span className="vh-kind">Controlled concepts and source wording</span><h3>Events and activities</h3><p>Documented organ work, performances and other activities, including wording retained without a controlled mapping.</p><a href="/vocab/modavis_activity_types">Browse {schemes.data?.items.find((x:Row)=>x.code==='modavis_activity_types')?.conceptCount??'…'} controlled concepts</a><a href={usageLink('activities')}>Browse recorded event wording</a><a href={usageLink('activities','Dankesbrief')}>Example: Dankesbrief</a></article><article><span className="vh-kind">Source wording and candidate concepts</span><h3>Stops</h3><p>Source stop designations with their pitches, divisions and separate specification accounts. Matching names do not prove equivalent stops.</p><a href={usageLink('stops')}>Browse stop terminology</a><a href={usageLink('stops','Vox Humana')}>Example: Vox Humana</a><a href={usageLink('stops','Principal')}>Candidate example: Principal</a></article><article><span className="vh-kind">Source wording</span><h3>Divisions</h3><p>Recorded division names and their use in instrument specifications.</p><a href={usageLink('divisions')}>Browse division terminology</a><a href={usageLink('divisions','Swell')}>Example: Swell</a></article><article><span className="vh-kind">Controlled concepts</span><h3>People and roles</h3><p>Occupations, activity roles and institutional contexts in the published vocabulary subset.</p><a href="/vocab/modavis_person_terminology">Browse person terminology</a><a href="/persons">Explore related people</a></article><article><span className="vh-kind">Separate reference dataset</span><h3>Instrument names and classifications</h3><p>Explore OMARO’s MIMO-derived names, Hornbostel–Sachs classification and assertion ontology. These do not assign classifications to POD organs.</p><a href="/vocab/omaro">Instrument names</a><a href="/vocab/omaro?collection=hs">Hornbostel–Sachs</a><a href="/vocab/omaro?collection=ontology">OMARO ontology</a></article><article><span className="vh-kind">Schema categories</span><h3>Entity types</h3><p>Person and organization categories used by the public schema, counted separately from governed vocabulary concepts.</p><a href="/vocab/modavis_entity_types">Browse entity types</a></article></div>
 <details className="vh-context"><summary>Vocabulary status, versions and downloads</summary><p>Controlled concepts carry established vocabulary identifiers. Candidate concepts and source wording remain explicitly separate. An occurrence is one retained source observation; multiple accounts may describe the same organ.</p>{schemes.error&&<p role="alert">{schemes.error}</p>}{schemes.data?.items.map((s:Row)=><p key={s.code}><a href={'/vocab/'+encodeURIComponent(s.code)}>{s.name}</a> · {s.version||'Schema categories'} · {s.conceptCount||s.categoryCount} {s.recordKind==='schema_categories'?'categories':'controlled concepts'}{s.snapshot&&<> · <a href={s.snapshot.metadataUrl}>Snapshot, citation and downloads</a></>}</p>)}<a href="/vocab/omaro">OMARO’s separate reference version and distributions</a>{releases.data?.items.map((r:Row)=><p key={r.id||r.versionLabel}><a href={'/vocab/releases/'+encodeURIComponent(r.versionLabel||r.mdvsId||String(r.id))}>Vocabulary release {r.versionLabel||r.vocabularyVersion||r.mdvsId}</a></p>)}{releases.error&&<p role="alert">{releases.error}</p>}</details></section>;
}
export function VocabularyUsage({family}:{family:string}){const [search,setSearch]=useState(location.search);const p=new URLSearchParams(search);const term=p.get('term');const [notice,setNotice]=useState('');const usageParams=new URLSearchParams(p);for(const key of ['view','groupBy','distributionPage','zeros','analysis'])usageParams.delete(key);const api='/api/vocab/usage/'+encodeURIComponent(family)+'?'+usageParams;const {data,error}=useData(api);
 useEffect(()=>{const f=()=>setSearch(location.search);window.addEventListener('popstate',f);return()=>window.removeEventListener('popstate',f)},[]);
 useEffect(()=>{if(data&&!p.has('snapshot')){const next=new URLSearchParams(search);next.set('snapshot',data.publicCoreSha256);history.replaceState({},'',location.pathname+'?'+next);setSearch(location.search)}},[data,search]);
 function go(values:Row){const next=new URLSearchParams(search);for(const [k,v] of Object.entries(values)){if(v===null||v==='')next.delete(k);else next.set(k,String(v))}history.pushState({},'',location.pathname+'?'+next);setSearch(location.search);setNotice('')}
 const pager=data&&<nav className="vh-pager" aria-label="Terminology result pages"><button disabled={data.offset===0} onClick={()=>go({page:Math.max(0,Number(p.get('page')||0)-1)})}>Previous</button><span>{n(data.total)} {term?(p.get('section')==='organs'?'organs':'occurrences'):'wordings'} · {data.total?data.offset+1:0}–{Math.min(data.total,data.offset+data.items.length)}</span><button disabled={!data.hasMore} onClick={()=>go({page:Number(p.get('page')||0)+1})}>Next</button></nav>;
 return <section className="vh-page" aria-label="Source terminology browser"><a href="/vocab">← All vocabularies</a>{term&&<p><a href={usageLink(family)+'?'+new URLSearchParams({snapshot:p.get('snapshot')||''})}>← {families[family]} wordings</a></p>}<header className="vh-hero"><p className="eyebrow">{term?'Recorded source wording':'Source terminology'}</p><h2>{term||families[family]||'Unknown collection'}</h2><p>{term?'Follow this wording to its recorded uses. No new vocabulary concept or definition is inferred.':'Browse wording recorded in the published source evidence. Case and spacing are grouped for lookup; original labels remain available.'}</p></header>
 {!term&&<form className="vh-search" key={search} onSubmit={e=>{e.preventDefault();go({q:new FormData(e.currentTarget).get('q'),sort:new FormData(e.currentTarget).get('sort'),page:0})}}><label>Search {families[family]}<input name="q" defaultValue={p.get('q')||''} maxLength={200}/></label><label>Order<select aria-label="Order" name="sort" defaultValue={p.get('sort')||'frequency'}><option value="frequency">Most recorded first</option><option value="alphabetical">Alphabetical</option></select></label><button type="submit">Search wording</button></form>}
 {term&&<form className="vh-search" key={'organ:'+search} role="search" aria-label="Search related organs" onSubmit={e=>{e.preventDefault();go({organ_q:String(new FormData(e.currentTarget).get('organ_q')||'').trim(),page:0})}}><label>Search related organs<input type="search" name="organ_q" defaultValue={p.get('organ_q')||''} maxLength={200} placeholder="Organ name or MODAVIS ID" aria-describedby="organ-search-help"/></label><button type="submit"><Search size={16}/>Search organs</button>{p.get('organ_q')&&<button type="button" onClick={()=>go({organ_q:null,page:0})}>Clear organ search</button>}</form>}
 {term&&<p id="organ-search-help">Search all organs in this term selection by their displayed name or identifier. Country, source and wording filters stay applied.</p>}
 {error&&<p role="alert">{error}{p.get('source')&&<button onClick={()=>go({source:null,page:0})}>Include all sources</button>}{term&&<> <button onClick={()=>go({match:'contains',page:0})}>Search wording containing this text</button></>}</p>}{!data&&!error&&<p role="status">Loading terminology evidence…</p>}
 {data&&<>{!term&&data.candidateConcepts?.length>0&&<details className="vh-context"><summary>Candidate concepts and definitions · {data.candidateConcepts.length}</summary><p>Accepted lexical mappings support these candidate concepts. They have not been promoted to the controlled vocabulary.</p>{data.candidateConcepts.map((x:Row)=><article key={x.id}><h3>{x.label.en}</h3><p>{x.definition}</p>{x.mappings.filter((m:Row)=>m.family===family).flatMap((m:Row)=>m.literals).map((word:string)=><p key={word}><a href={usageLink(family,word)}>{word}: inspect recorded uses</a></p>)}<Evidence value={x}/></article>)}</details>}{term&&<><div className="vh-stats"><span><strong>{n(data.counts.occurrences)}</strong> source occurrences</span><span><strong>{n(data.counts.organs)}</strong> distinct organs</span><span><strong>{n(data.counts.sourceRecords)}</strong> source records</span><span><strong>{n(data.counts.wordings)}</strong> original {data.counts.wordings===1?'wording':'wordings'}</span></div><div className="vh-controls"><label>Match mode<select aria-label="Match mode" value={p.get('match')||'exact'} onChange={e=>go({match:e.target.value,page:0,distributionPage:0})}><option value="exact">Exact wording</option><option value="contains">Wording containing this text</option></select></label><label>Source<select aria-label="Source" value={p.get('source')||''} onChange={e=>go({source:e.target.value,page:0,distributionPage:0})}><option value="">All sources</option>{data.sourceOptions.map((x:Row)=><option key={x.source_key} value={x.source_key}>{x.source_key} · {n(x.occurrences)}</option>)}</select></label><label>Show<select aria-label="Show" value={p.get('section')||'occurrences'} onChange={e=>go({section:e.target.value,page:0})}><option value="occurrences">Source occurrences</option><option value="organs">Distinct related organs</option></select></label></div><p>{data.match==='exact'?'Exact lookup ignores case and repeated spaces; punctuation and additional words remain significant.':'This is a broader text search, not a grouping of equivalent terms.'} Original accounts and reported dates remain separate.{family==='stops'&&<> <a href="#faq-stop-matching">Missing an expected stop? Search FAQ</a></>}</p>
 <details><summary>Original wordings and mappings</summary>{data.variants.map((v:Row)=><p key={v.label}><a href={v.href}>{v.label}</a> · {n(v.occurrences)} occurrences</p>)}{data.variantsTruncated&&<p>Showing the first 30 original wordings; the complete evidence export retains every occurrence.</p>}{data.mappings.map((m:Row,i:number)=><article key={i}><strong>{m.status==='controlled'?'Controlled mapping':m.status==='candidate'?'Candidate concept · accepted lexical mapping':'Unmapped source wording'}</strong> · {n(m.occurrences)} occurrences{m.href&&<p><a href={m.href}>{m.definition.preferredLabel||m.concept}</a></p>}{m.status==='candidate'&&<p>{m.definition.definition}</p>}<Evidence value={m}/></article>)}</details>
 <div className="vh-controls"><button onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+data.href);setNotice('Snapshot-bound term link copied.')}catch{setNotice('Copy the term link below.')}}}><Copy size={16}/>Copy term link</button><a href={data.href}>Snapshot-bound term link</a>{data.counts.occurrences<=50000?<a href={api.replace('?','/export?')} download="modavis-source-terminology.json"><Download size={16}/>Download complete occurrence evidence</a>:<p>Complete downloads support up to 50,000 occurrences. Choose exact wording or a source to narrow this selection.</p>}</div>{notice&&<p role="status">{notice}</p>}</>}
 {term&&(p.get("organ_q")?.trim()?<p className="rx-warning">Distributions are available for the full term and source selection. Clear the organ search to explore them.</p>:<TermDistribution family={family} search={search} go={go}/>)}
 {p.get('dimension')&&<p className="rx-warning">Occurrence list filtered by {p.get('dimension')}: {p.get('bucket')?.replace(/^[a-z]:/,'')}. <button onClick={()=>go({dimension:null,bucket:null,page:0})}>Clear group filter</button></p>}
 {pager}{!data.total&&<p>{term?'No organs match this selection. Try another name or identifier, or clear the organ search.':'No source wording matches this search. Try another spelling or clear the search.'}</p>}<div className="vh-results">{data.items.map((x:Row,i:number)=><article key={(x.id||x.key||x.organ)+':'+i}>{!term?<><h3><a href={x.href}>{x.label}</a></h3><p>{n(x.occurrences)} source occurrences · open to inspect related organs and sources</p></>:p.get('section')==='organs'?<><h3><a href={x.href}>{x.label}</a></h3><p>{n(x.occurrences)} matching occurrences</p></>:<><h3><a href={x.href}>{x.label}</a></h3><p><a href={x.organHref}>{x.organLabel}</a></p><p>{family==='activities'?'Event':(x.pitch||'Pitch unrecorded')+' · '+(x.division||'Division unrecorded')} · {x.year??'Date unestablished'} · {String(x.date_kind||'').replace(/_/g,' ')}</p><p>Source: {x.source_key}{x.sourceEvidence?.source_url&&<> · <a href={x.sourceEvidence.source_url} target="_blank" rel="noreferrer">Original source</a></>}</p><Evidence value={x}/></>}</article>)}</div>{pager}<details className="vh-context"><summary>Method and citation</summary><p>{data.method}</p><p>These are application views over POD 1.6.0 evidence, not new canonical vocabulary identifiers.</p><JsonEvidence value={{publicCoreSha256:data.publicCoreSha256,researchIndexSha256:data.researchIndexSha256,methodSha256:data.methodSha256,selectionSha256:data.selectionSha256}} label="Terminology citation"/></details></>}
 </section>;
}
